name: Update Pyproject version
on:
  pull_request:
    types: [opened, ready_for_review]
    branches:
      - devel

jobs:
  update-version:
    name: Modify project version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
        run: |
          curl -O -sSL https://install.python-poetry.org/install-poetry.py
          python install-poetry.py -y --version 1.1.13
          echo "PATH=${HOME}/.poetry/bin:${PATH}" >> $GITHUB_ENV
          rm install-poetry.py
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
          cache: 'poetry'
      - run: |
          poetry env use 3.9
          poetry install
      - name: Update pyproject.toml
        run: |
          poetry version minor
          echo "PROJECT_VERSION=$(poetry version | awk '{print $2}')" >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update pyproject.toml v${{ env.PROJECT_VERSION }}
          branch: create-pull-request/release
          base: devel
          delete-branch: true
          title: Update pyproject.toml v${{ env.PROJECT_VERSION }}
          body: |
            Update pyproject version
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          labels: release
          assignees: saorio
